stages:
  - dependencies
  - prepare
  - build
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'

default:
  tags:
    - "mais"
  image: node:18

cache:
  key: node_modules
  paths:
    - node_modules/

dependencies:
  stage: dependencies
  before_script:
    - echo "Install dependencies..."
  script:
    - npm ci

prepare:
  stage: prepare
  dependencies:
    - dependencies
  before_script:
    - echo "Prepare for build..."
  script:
    - npm run postinstall
  artifacts:
    paths:
      - .nuxt/
    expire_in: 1 hour

build:
  stage: build
  dependencies:
    - prepare
  before_script:
    - echo "Building..."
  script:
    - npm run build
  artifacts:
    paths:
      - .nuxt/
      - .output/
      - configs/
    expire_in: 1 hour

deploy:
  stage: deploy
  image: docker:latest
  tags:
    - "helios"
  dependencies:
    - build
  before_script:
    - echo "Deploying..."
    - export NUXT_PORT="3015"
  script:
    - docker compose up --detach --build